In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load Dataset
df = pd.read_csv("../Data/student_placement_prediction_dataset_2026.csv")

In [3]:
df.head()

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,72.647009,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,Not Placed,0.00
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,61.699110,88.887600,1,73.694605,60.198856,No,4.4,2.3,Not Placed,0.00
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed,11.99
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,58.401069,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,Not Placed,0.00
4,5,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,...,74.489201,79.120749,1,0.000000,67.268893,No,8.7,3.4,Placed,12.16

In [4]:
# checking missing values
df.isnull().sum()

student_id                   0
age                          0
gender                       0
cgpa                         0
branch                       0
college_tier                 0
internships_count            0
projects_count               0
certifications_count         0
coding_skill_score           0
aptitude_score               0
communication_skill_score    0
logical_reasoning_score      0
hackathons_participated      0
github_repos                 0
linkedin_connections         0
mock_interview_score         0
attendance_percentage        0
backlogs                     0
extracurricular_score        0
leadership_score             0
volunteer_experience         0
sleep_hours                  0
study_hours_per_day          0
placement_status             0
salary_package_lpa           0
dtype: int64

In [5]:
# checking duplicates rows
df.duplicated().sum(0)

np.int64(0)

In [6]:
df.columns

Index(['student_id', 'age', 'gender', 'cgpa', 'branch', 'college_tier',
       'internships_count', 'projects_count', 'certifications_count',
       'coding_skill_score', 'aptitude_score', 'communication_skill_score',
       'logical_reasoning_score', 'hackathons_participated', 'github_repos',
       'linkedin_connections', 'mock_interview_score', 'attendance_percentage',
       'backlogs', 'extracurricular_score', 'leadership_score',
       'volunteer_experience', 'sleep_hours', 'study_hours_per_day',
       'placement_status', 'salary_package_lpa'],
      dtype='object')

In [7]:
# Drop unnecessary columns
df.drop("student_id", axis=1, inplace=True)

In [8]:
df.head()

,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,aptitude_score,...,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa
0,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,81.707722,...,72.647009,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,Not Placed,0.00
1,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,63.116715,...,61.699110,88.887600,1,73.694605,60.198856,No,4.4,2.3,Not Placed,0.00
2,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,48.658753,...,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed,11.99
3,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,66.376653,...,58.401069,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,Not Placed,0.00
4,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,61.274985,...,74.489201,79.120749,1,0.000000,67.268893,No,8.7,3.4,Placed,12.16

In [9]:
# Converting the placement labels into numbers.
df["placement_status"] = df["placement_status"].map({
    "Placed" : 1,
    "Not Placed" : 0
})

In [10]:
df.placement_status.value_counts()

placement_status
1    54459
0    45541
Name: count, dtype: int64

In [11]:
# Separating Features and Targets
x = df.drop(["placement_status", "salary_package_lpa"], axis=1)
y_class = df["placement_status"]
y_reg = df["salary_package_lpa"]

In [ ]:
x.select_dtypes(include="object").columns

Index(['gender', 'branch', 'college_tier', 'volunteer_experience'], dtype='object')

In [ ]:
# Encoding of Categorical Features
x = pd.get_dummies(x, drop_first=True)

In [14]:
x.head()

,age,cgpa,internships_count,projects_count,certifications_count,coding_skill_score,aptitude_score,communication_skill_score,logical_reasoning_score,hackathons_participated,...,study_hours_per_day,gender_Male,branch_Civil,branch_ECE,branch_EEE,branch_IT,branch_Mechanical,college_tier_Tier 2,college_tier_Tier 3,volunteer_experience_Yes
0,24,7.53,4,6,1,99.238568,81.707722,57.707166,59.070073,4,...,3.6,True,False,False,False,True,False,True,False,True
1,21,7.92,1,3,6,80.966123,63.116715,59.197085,78.976419,0,...,2.3,True,False,False,False,False,False,True,False,False
2,22,8.60,0,1,1,49.177184,48.658753,92.104885,80.603331,0,...,5.9,False,False,False,True,False,False,False,False,False
3,24,6.68,0,2,2,79.359084,66.376653,83.411798,64.187246,1,...,4.4,True,False,False,False,False,False,False,False,True
4,20,8.43,1,4,3,65.018573,61.274985,88.956331,56.163678,1,...,3.4,False,False,False,False,True,False,False,True,False

In [15]:
feature_columns = x.columns

In [16]:
# Saving feature names
import pickle

pickle.dump(feature_columns, open("../models/feature_columns.pkl", "wb"))

In [17]:
# Scaling Numerical Features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [18]:
# Saving the scaler
pickle.dump(scaler, open("../models/scaler.pkl", "wb"))

In [19]:
# Train-Test Split (Classification)

from sklearn.model_selection import train_test_split
x_train_cls, x_test_cls, y_train_cls, y_test_cls = train_test_split(x_scaled, y_class, test_size=0.2, random_state=42, stratify=y_class)

In [20]:
# Train-Test Split (Regression)
placed_df = df[df["placement_status"] == 1]

In [24]:
# Separation of features and targets
x_reg = placed_df.drop(["placement_status", "salary_package_lpa"], axis=1)
y_reg = placed_df["salary_package_lpa"]

In [ ]:
# Encoding of Categorical Features
x_reg = pd.get_dummies(x_reg, drop_first=True)

In [28]:
x_reg = x_reg.reindex(columns=feature_columns, fill_value=0)

In [29]:
x_reg.head()

,age,cgpa,internships_count,projects_count,certifications_count,coding_skill_score,aptitude_score,communication_skill_score,logical_reasoning_score,hackathons_participated,...,study_hours_per_day,gender_Male,branch_Civil,branch_ECE,branch_EEE,branch_IT,branch_Mechanical,college_tier_Tier 2,college_tier_Tier 3,volunteer_experience_Yes
2,22,8.60,0,1,1,49.177184,48.658753,92.104885,80.603331,0,...,5.9,False,False,False,True,False,False,False,False,False
4,20,8.43,1,4,3,65.018573,61.274985,88.956331,56.163678,1,...,3.4,False,False,False,False,True,False,False,True,False
5,22,7.44,1,5,1,49.758865,45.252593,51.881728,69.984592,3,...,3.4,True,False,False,False,False,False,True,False,False
8,19,8.52,2,5,0,100.000000,93.987115,75.165144,87.737986,0,...,4.2,True,False,False,False,False,True,True,False,False
9,20,8.07,2,2,2,93.421972,71.379374,57.215196,58.628985,0,...,4.5,False,True,False,False,False,False,True,False,False

In [30]:
x_reg = scaler.transform(x_reg)

In [32]:
x_train_reg, x_test_reg, y_train_reg, y_test_reg = train_test_split(
    x_reg,
    y_reg,
    test_size=0.2,
    random_state=42
)

In [33]:
print(x_train_cls.shape)
print(x_test_cls.shape)

print(x_train_reg.shape)
print(x_test_reg.shape)

(80000, 28)
(20000, 28)
(43567, 28)
(10892, 28)

In [34]:
# Save Classification Data
pickle.dump(x_train_cls, open("../models/x_train_cls.pkl", "wb"))
pickle.dump(x_test_cls, open("../models/x_test_cls.pkl", "wb"))
pickle.dump(y_train_cls, open("../models/y_train_cls.pkl", "wb"))
pickle.dump(y_test_cls, open("../models/y_test_cls.pkl", "wb"))

# Save Regression Data
pickle.dump(x_train_reg, open("../models/x_train_reg.pkl", "wb"))
pickle.dump(x_test_reg, open("../models/x_test_reg.pkl", "wb"))
pickle.dump(y_train_reg, open("../models/y_train_reg.pkl", "wb"))
pickle.dump(y_test_reg, open("../models/y_test_reg.pkl", "wb"))